<?php

namespace Database\Seeders;

use App\Models\Catalogs\Province;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProvinceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $provinces = [
            [
                'code' => Province::DEFAULT,
                'name' => 'San Luis',
                'logo1' => null,
                'logo2' => null,
                'title' => 'Ministerio de Educación',
                'subtitle' => 'Forjamos el futuro a través de la educación, cimiento sólido para el progreso de la provincia de San Luis.',
                'link' => 'https://sanluis.gov.ar/educacion/',
                'config' => json_encode([
                    "header" => [
                        "background-color" => "#f0dea1",
                        "color" => "#333"
                    ]
                ]),
            ],
            [
                'code' => 'mza',
                'name' => 'Mendoza',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'cba',
                'name' => 'Córdoba',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'sj',
                'name' => 'San Juan',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'lr',
                'name' => 'La Rioja',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'bsas',
                'name' => 'Buenos Aires',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'caba',
                'name' => 'Ciudad Autónoma de Buenos Aires',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'cat',
                'name' => 'Catamarca',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'cha',
                'name' => 'Chaco',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'chu',
                'name' => 'Chubut',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'cor',
                'name' => 'Corrientes',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'ent',
                'name' => 'Entre Ríos',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'for',
                'name' => 'Formosa',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'juj',
                'name' => 'Jujuy',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'lpa',
                'name' => 'La Pampa',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'mis',
                'name' => 'Misiones',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'neu',
                'name' => 'Neuquén',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'rng',
                'name' => 'Río Negro',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'sal',
                'name' => 'Salta',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'sct',
                'name' => 'Santa Cruz',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'sfe',
                'name' => 'Santa Fe',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'sde',
                'name' => 'Santiago del Estero',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'tfu',
                'name' => 'Tierra del Fuego',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
            [
                'code' => 'tuc',
                'name' => 'Tucumán',
                'logo1' => null,
                'logo2' => null,
                'title' => null,
                'subtitle' => null,
                'link' => null,
                'config' => null,
            ],
        ];

        foreach ($provinces as $i => $province) {
            $province['order'] = $i;
            Province::create($province);
        }
    }
}
